name: dotnet package

on:
  release:
    types: [created]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # SDK Version to use.
        # source-url: https://nuget.pkg.github.com/<owner>/index.json
    - name: Create the package
      run: dotnet pack src/Stac.Api.Package/ -c Release --include-symbols -o publish
    - name: Publish the package to Nuget
      run: dotnet nuget push publish/*.nupkg -s https://www.nuget.org/api/v2/package -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
    - name: Remove symbols
      run: rm publish/*.symbols.nupkg
    - name: Publish the package to GPR
      run: dotnet nuget push publish/*.nupkg --no-symbols -s https://nuget.pkg.github.com/Terradue/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install nbconvert
    - name: Convert notebooks to Markdown
      run: find docs/notebooks -type f -name "*.ipynb" -exec python -m nbconvert --to markdown {} \;
    - name: Set proper snippet language
      run: find docs/notebooks -type f -name "*.md" -exec sed -i 's/polyglot-notebook/csharp/g' {} \;
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docs/docfx.json
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_site
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2